# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: youtube-clone-app
#   labels:
#     app: youtube-clone-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: youtube-clone-app
#   template:
#     metadata:
#       labels:
#         app: youtube-clone-app
#     spec:
#       terminationGracePeriodSeconds: 30
#       containers:
#       - name: youtube-clone-app
#         image: ashfaque9x/youtube-clone:latest
#         imagePullPolicy: "Always"
#         ports:
#         - containerPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-clone
  template:
    metadata:
      labels:
        app: youtube-clone
    spec:
      containers:
      - name: youtube-clone
        image: hlaingminpaing/youtube-clone:v1.3  # This will be updated dynamically
        ports:
        - containerPort: 80